require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'test/dummy/**/*'
    - 'db/schema.rb'
    - 'lib/generators/**/templates/**/*'

Naming/FileName:
  Exclude:
    - 'lib/reactive-actions.rb'

Style/Documentation:
  Enabled: true

Layout/LineLength:
  Max: 200
  # Exclude spec files from line length checks
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/BlockLength:
  Max: 30
  # Exclude spec files from block length checks
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/**/*.rake'

Metrics/ModuleLength:
  Max: 150
  # Exclude spec files from module length checks
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 320

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

# RSpec specific configurations
RSpec/DescribeClass:
  Enabled: true

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 7